"""fixes in rating and report model

Revision ID: 391a5190da47
Revises: 474007de7d80
Create Date: 2025-02-20 00:49:12.578378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391a5190da47'
down_revision = '474007de7d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('VERYBAD', 'BAD', 'MEDIUM', 'GOOD', 'VERYGOOD', name='rating'),
               existing_nullable=False)

    with op.batch_alter_table('Like', schema=None) as batch_op:
        batch_op.alter_column('tweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reply_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Report', schema=None) as batch_op:
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')

    with op.batch_alter_table('Like', schema=None) as batch_op:
        batch_op.alter_column('reply_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Enum('VERYBAD', 'BAD', 'MEDIUM', 'GOOD', 'VERYGOOD', name='rating'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
